name: mksc_mobile
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  ionicons: ^0.2.2
  flutter_svg: ^2.0.10+1
  syncfusion_flutter_charts: ^25.1.38
  http: ^1.2.1
  provider: ^6.1.2
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.5
  remove: ^1.0.10
  popover: ^0.3.0
  shared_preferences: ^2.2.3
  video_player: ^2.8.6
  shimmer: ^3.0.0
  flutter_html: ^3.0.0-beta.2
  chewie: ^1.2.2
  numberpicker: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/logo.jpeg
    - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
